"""
Builds a polished Word document report from a completed scan + interview +
prioritization run — the human-readable deliverable, as opposed to
scan_report.json (machine-readable, kept alongside it for automation/reuse).
"""
import docx
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.shared import Pt, RGBColor

PRIORITY_COLORS = {
    "Critical": RGBColor(0xC0, 0x00, 0x00),
    "High": RGBColor(0xC5, 0x5A, 0x00),
    "Medium": RGBColor(0x9A, 0x7D, 0x00),
    "Low": RGBColor(0x2E, 0x7D, 0x32),
}


def _add_controls_table(doc, controls):
    table = doc.add_table(rows=1, cols=4)
    table.style = "Light Grid Accent 1"
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = "Priority", "Control", "Score", "Why"

    for c in controls:
        row = table.add_row().cells
        priority_run = row[0].paragraphs[0].add_run(c["priority"])
        priority_run.bold = True
        priority_run.font.color.rgb = PRIORITY_COLORS.get(c["priority"], RGBColor(0, 0, 0))
        row[1].text = c["control_id"]
        row[2].text = f"{c['adjusted_score']:.2f}"
        row[3].text = "\n".join(f"- {r}" for r in c["reasons"])
    return table


def build_report(path, final_report, baseline_prioritized, context, executive_summary,
                  drafts=None, scan_report=None):
    drafts = drafts or {}
    doc = docx.Document()

    doc.add_heading("Security Control Assessment Report", level=0)
    doc.add_heading(context.get("business_name", "Unnamed Organization"), level=1)

    meta = doc.add_paragraph()
    meta.add_run("Scan target(s): ").bold = True
    meta.add_run(final_report.get("cidr", "unspecified"))
    meta.add_run("\nEnvironment: ").bold = True
    meta.add_run(
        f"{context.get('sector', 'unspecified')} sector, "
        f"security program maturity reported as {context.get('maturity', 'unspecified')}, "
        f"internet-facing: {context.get('internet_facing', 'unspecified')}"
    )

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(executive_summary)

    if scan_report and scan_report.get("results"):
        doc.add_heading("Devices Found", level=1)
        table = doc.add_table(rows=1, cols=5)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        for i, label in enumerate(["IP Address", "Hostname", "Device Type", "MAC / Vendor", "Open Services"]):
            hdr[i].text = label
        for host in scan_report["results"]:
            row = table.add_row().cells
            row[0].text = host["ip"]
            row[1].text = host.get("hostname") or "-"
            row[2].text = host.get("device_type_guess", "-")
            row[3].text = f"{host['mac_address']} ({host['vendor']})" if host.get("mac_address") else "not available"
            row[4].text = ", ".join(f"{s['service']}:{s['port']}" for s in host["services"])

    doc.add_heading("Controls Required Based on Discovered Systems", level=1)
    for host in final_report["hosts"]:
        doc.add_heading(f"{host['ip']}  (categories: {', '.join(host['categories'])})", level=2)
        all_controls = [c for controls in host["recommended_controls"].values() for c in controls]
        all_controls.sort(key=lambda c: c["adjusted_score"], reverse=True)
        _add_controls_table(doc, all_controls)

    doc.add_heading("Baseline Controls Recommended for Every Environment", level=1)
    doc.add_paragraph(
        "Not tied to a specific scan finding — optional, but recommended for best security; "
        "priority reflects the environment context gathered during the interview."
    )
    _add_controls_table(doc, baseline_prioritized)

    if drafts:
        doc.add_heading("Draft Policy Language", level=1)
        doc.add_paragraph(
            "AI-generated starting point for each control below — review, verify, and adapt "
            "before adopting as official policy."
        )
        for control_id, text in drafts.items():
            doc.add_heading(control_id, level=2)
            doc.add_paragraph(text)

    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        "Generated by Control Advisor. Draft language and prioritization are AI-assisted "
        "and should be reviewed by a qualified professional before use."
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    doc.save(path)
